language: python
services:
  - docker
python:
  - "2.7"
install:
  - make deps
script:
  - make test_xunit
  - make lint
  - make docker_build
  - make docker_push

deploy:
  provider: heroku
  app: arcane-basin-85738
  api_key: ${HEROKU_API_KEY}
